version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank-transfer-api
    ports:
      - "8000:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: 123

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: 123
    ports:
      - "5440:5432"  #
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: