spring:
  application:
    name: project

  datasource:
    url: jdbc:postgresql://localhost:5433/userdb  # Update with your PostgreSQL URL
    driver-class-name: org.postgresql.Driver
    username: postgres  # Your PostgreSQL username
    password: 1234  # Your PostgreSQL password

  # Remove or disable H2 Console configuration if not using H2
  h2:
    console:
      enabled: false  # Set to false if you're not using H2 console

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # Options: create, create-drop, update, validate, none
    show-sql: true
    open-in-view: true

  # Optionally, configure Flyway or Liquibase for managing schema changes
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml